Sources/parser/EpubParser.swift
Sources/parser/SMILParser.swift

Closes readium/r2-testapp-swift#4 
Fixes this crash issue triggered by nil value. Improve the parsing logic for audio clip inside SMIL file.
This PR relays on another [PR](https://github.com/readium/r2-shared-swift/pull/4)
In the old code, it will ignore any audio element which doesn't have both clipBegin and clipEnd. That's logically wrong. This PR changed it to correct logic, it also fixed the nil value crash as well.

Fix the parsing logic of audio clip

---

Sources/parser/EpubParser.swift

This is a quick fix for duplicated TOC content when loading LCP book.
The reason is clean. It's appending TOC content each time when loading then book.
While, it has the same appending logic for all the other properties. That's looks quite strange.
Need more research later for potential risk.

Quick fix for #63 duplicated TOC of LCP book

---

R2Streamer/touchHandling.js

All the Input nodes should be ignored under custom touch handling. Otherwise there will be endless trouble. This PR ignored all the Input nodes, so Webkit could handle them in the proper way.
Fix issue https://github.com/readium/r2-testapp-swift/issues/8

Ignore input element for touch handling

---

R2Streamer/ReadiumCSS-after.css
R2Streamer/ReadiumCSS-before.css
R2Streamer/ReadiumCSS-default.css
R2Streamer/utils-old.js
Sources/fetcher/ContentFilter.swift
r2-streamer-swift.xcodeproj/project.pbxproj

iOS 9 doesn't support some ES6 features, so we got this bug. Settings menu doesn't work.
https://github.com/readium/r2-testapp-swift/issues/47
This PR fixed issue by creating separated JS file for ES5, then it for iOS 9.

Use ES5 code for iOS9

---

Sources/model/Container.swift
Sources/model/ContainerCbz.swift
Sources/model/ContainerCbzDirectory.swift
Sources/model/ContainerEpub.swift
Sources/model/ContainerEpubDirectory.swift
Sources/parser/CbzParser.swift
Sources/parser/EpubParser.swift
Sources/server/PublicationServer.swift

As discussed, the app will use last updated date descending as sorting order.
This PR is not using SQLite, the updated date came from iOS file system directly.
SQLite version will come later with good duplication check for different kinds of books.

Expose updated date and use it for sorting

---

R2Streamer/scripts/touchHandling.js
R2Streamer/scripts/utils-old.js
R2Streamer/scripts/utils.js
Sources/fetcher/ContentFilter.swift

Fix readium/r2-testapp-swift#137 - FXL: width seems to be too wide and therefore scrollable
Fix readium/r2-testapp-swift#138 - FXL: tap gestures seem to interfere with drag gestures
- Remove the artificially injected viewport when opening a FXL publication to prevent extra spacing
- Position calculation of a tap gesture is updated. Previous calculation for an FXL publication in zoomed mode was always wrong.
- For an FXL publication, scrolling events (left and right) was not handled correctly. This PR fixes this.

Fix layout and scrolling issues for FXL publications

---

R2Streamer/scripts/utils-old.js
R2Streamer/scripts/utils.js

Fixes readium/r2-testapp-swift#147
This PR basically resolves the issue by adding a missing call to the `snapOffset` method.

Fixes #147,  landing between columns issue

---

Sources/parser/OPFParser.swift

This PR simply added a filter to ignore any `dc:date` with any property. It's relying on the date format check in https://github.com/readium/r2-shared-swift/pull/33

Add filter for dc:date

---

R2Streamer/scripts/touchHandling.js
R2Streamer/scripts/utils-old.js
R2Streamer/scripts/utils.js
Sources/fetcher/ContentFilter.swift

Fix the touch problem under CJK-vertical, 
` var position = touch.clientX / window.innerWidth;`
Fix a problem of scrolling on the edge of FXL content. In some case, it cannot reach the exact edge of FXL. So it cannot scroll to another FXL content by tapping.

Fix the touch problem under CJK-vertical

---

r2-streamer-swift/Fetcher/ContentFilter.swift
r2-streamer-swift/Fetcher/DRM/CBCDRMInputStream.swift
r2-streamer-swift/Fetcher/DRM/DRMInputStream.swift
r2-streamer-swift/Fetcher/DRM/FullDRMInputStream.swift
r2-streamer-swift/Parser/EPUB/EPUBParser.swift
r2-streamer-swift/Parser/PDF/PDFFileCGParser.swift
r2-streamer-swift/Parser/PDF/PDFParser.swift
r2-streamer-swift/Toolkit/DataExtension.swift

1. Reading an `InputStream` with a `maxLength` bigger than EOF must be authorized, which was not the case in the DRM input streams.
2. Fix creating the `positionList` with LCPDF, which requires to parse the PDF with Core Graphics when parsing the `Publication` to get the number of pages. This fix is not entirely satisfying because we need to read the PDF fully instead of relying on random access with `CBCDRMInputStream` ([I opened an issue for this problem](https://github.com/readium/r2-streamer-swift/issues/141)).
https://github.com/readium/r2-streamer-swift/blob/1de6db2cf5c72e88384d238454a6fd8b9746022f/r2-streamer-swift/Parser/PDF/PDFParser.swift#L193-L197

Fix DRM input streams and positionList for LCPDF

---

r2-streamer-swift/Parser/CBZ/CBZParser.swift

`application/x-cbr` is deprecated.
https://www.iana.org/assignments/media-types/application/vnd.comicbook+zip

Fix CBZ media type

---

r2-streamer-swift.xcodeproj/project.pbxproj
r2-streamer-swift/Fetcher/ContentFilter.swift
r2-streamer-swift/Fetcher/DRM/CBCDRMInputStream.swift
r2-streamer-swift/Fetcher/Fetcher.swift
r2-streamer-swift/Parser/CBZ/CBZContainer.swift
r2-streamer-swift/Parser/CBZ/CBZParser.swift
r2-streamer-swift/Parser/EPUB/EPUBContainerParser.swift
r2-streamer-swift/Parser/EPUB/EPUBEncryptionParser.swift
r2-streamer-swift/Parser/EPUB/EPUBMetadataParser.swift
r2-streamer-swift/Parser/EPUB/EPUBParser.swift
r2-streamer-swift/Parser/EPUB/NCXParser.swift
r2-streamer-swift/Parser/EPUB/NavigationDocumentParser.swift
r2-streamer-swift/Parser/EPUB/OPFMeta.swift
r2-streamer-swift/Parser/EPUB/OPFParser.swift
r2-streamer-swift/Parser/EPUB/SMILParser.swift
r2-streamer-swift/Parser/PDF/PDFContainer.swift
r2-streamer-swift/Parser/PDF/PDFFileParser.swift
r2-streamer-swift/Parser/PDF/PDFParser.swift
r2-streamer-swift/Parser/PublicationParser.swift
r2-streamer-swift/Parser/WEBPUB/WEBPUBParser.swift
r2-streamer-swift/Server/PublicationServer.swift
r2-streamer-swift/Toolkit/Extensions/Link.swift

See https://github.com/readium/r2-shared-swift/pull/88

Use the new Format API

---

r2-streamer-swift/Parser/PDF/PDFParser.swift
r2-streamer-swift/Toolkit/DataExtension.swift

The buffer length used to read a LCPDF was too small, which took ages to open a large one (> 50 MB).

Improve performances when opening large LCPDFs

---

r2-streamer-swift/Server/PublicationServer.swift

Encoded href for resources are not decoded and it failed if the publication is an archive (zipped audio book for instance).
The resource is not found in the archive.

Decode resource href before searching into archive

---

r2-streamer-swift/Streamer.swift

This allows to modify a `Publication` from a closure provided to `Streamer.open()`. For example, to merge the Publication metadata with some metadata pulled from a database or OPDS publication.
Compared to the `onCreatePublication` provided to `Streamer`'s constructor, this can be use to tailor the transformation to a particular publication, for example by using a db model in the transform.

Add onCreatePublication to Streamer.open()

---

CHANGELOG.md
r2-streamer-swift/Parser/Audio/AudioParser.swift
r2-streamer-swift/Parser/Audio/Services/AudioLocatorService.swift
r2-streamer-swift/Parser/EPUB/EPUBParser.swift
r2-streamer-swift/Parser/EPUB/Resource Transformers/EPUBHTMLInjector.swift
r2-streamer-swift/Parser/Image/CBZParser.swift
r2-streamer-swift/Parser/Image/ImageParser.swift
r2-streamer-swift/Parser/PDF/PDFParser.swift
r2-streamer-swift/Parser/PublicationParser.swift
r2-streamer-swift/Parser/Readium/ReadiumWebPubParser.swift
r2-streamer-swift/Streamer.swift
r2-streamer-swiftTests/Parser/Audio/AudioParserTests.swift
r2-streamer-swiftTests/Parser/EPUB/Services/EPUBPositionsServiceTests.swift
r2-streamer-swiftTests/Parser/Image/ImageParserTests.swift
r2-streamer-swiftTests/Parser/PublicationParsingTests.swift
r2-streamer-swiftTests/Parser/Readium/ReadiumWebPubParserTests.swift
r2-streamer-swiftTests/Server/PublicationServerTests.swift

* `Streamer` is now expecting a `PublicationAsset` instead of a `File`. You can create custom implementations of
`PublicationAsset` to open a publication from different medium, such as a file, a remote URL, in-memory bytes, etc.
* `FileAsset` can be used to replace `File` and provides the same behavior.

Replace File with PublicationAsset

---

CHANGELOG.md
r2-streamer-swift/Server/WebServerResourceResponse.swift

* The HTTP server now requests that publication resources are not cached by browsers.
* Caching poses a security risk for protected publications.

Disable HTTP caching when serving publication resources

---

r2-streamer-swift.xcodeproj/project.pbxproj

The debug build was compatible with XCFrameworks, but still failed while archiving with Xcode.

Fix archiving with Xcode

---

r2-streamer-swift/Server/PublicationServer.swift
r2-streamer-swift/Server/WebServerResourceResponse.swift
r2-streamer-swift/Toolkit/Extensions/Fetcher.swift
r2-streamer-swiftTests/Extensions.swift

* See https://github.com/readium/r2-shared-swift/pull/130 for the new Archive API.
* Resource is served directly instead of using the `ResourceInputStream` indirection.

Use the new Archive API and simplify serving a Resource from the HTTP server

---

CHANGELOG.md
r2-streamer-swift/Parser/EPUB/Resource Transformers/EPUBDeobfuscator.swift
r2-streamer-swiftTests/Fixtures/EPUBDeobfuscator/nav.xhtml
r2-streamer-swiftTests/Parser/EPUB/Resource Transformers/EPUBDeobfuscatorTests.swift

Fix crash when reading obfuscated resources with an empty publication ID
